GoogleCloudPlatform/guest-oslogin

src/oslogin_utils.cc
The group caching work was transferred from a long-lived development branch on the original repo; the eventual merge accidentally reverted this fix.
Was originally fixed in GoogleCloudPlatform/compute-image-packages#821
=> Correct JSON refcount decrementing (again)

src/nss/nss_cache_oslogin.c
Macro DECLARE_NSS_METHOD_TABLE was using function
_nss_cache_oslogin_endgrent(), but it doesn't exist, as the function is
called _nss_cache_endgrent().
Rename _nss_cache_endgrent() to _nss_cache_oslogin_endgrent() to match
the standard used in the file and fix the DECLARE_NSS_METHOD_TABLE which
is used in FreeBSD
=> Fix endgrent funtion name for FreeBSD

cron.d, packaging/google-compute-engine-oslogin.spec, src/Makefile
This cron file replaces time-based checks in the python guest. File naming is per distro specs.
=> add cron job for cache refresh

src/nss/nss_oslogin.cc
closes a potential open filehandle leak. the `initgroups` function is called on session creation.
=> close /etc/passwd in initgroups

src/nss/nss_cache_oslogin.c, src/nss/nss_oslogin.cc
Add the `O_CLOEXEC` flag to all `fopen()` calls. See `open (2)` for a description of this behavior change.
=> add CLOEXEC to fopen call

google_oslogin_control
Local user accounts can use these groups for privilege escallation. As a
short term remediation, we should stop adding all users to these groups
by default.
Relevant groups: `adm`, `docker`, and `lxd`.
=> Remove OS Login users from admin groups.

src/pam/pam_oslogin_login.cc
if index '0' is entered at the challenge selection screen, this will cause a segfault in the `pam_oslogin_login` module.
additionally, contrary to docs `pam_error` only sends message to the user and doesn't necessarily end the dialogue. add a return statement for every `pam_error` instance in this module.
=> correct index 0 bug

src/cache_refresh/cache_refresh.cc, src/include/compat.h, src/oslogin_utils.cc
Set passwords by default to "!". This is the default "locked" password. it is not a valid password, and it also is not "x" which has the special meaning of "consult the shadow file". 
This is to prevent passwordless `su` usage of OS Login accounts, except by root.
=> set passwords to !

src/cache_refresh/cache_refresh.cc, src/oslogin_utils.cc
This commit updates the logic in the cache_refresh binary with the
following behaviors, for both users and groups:
- If the metadata server returns successfully, but returns no users,
create an empty cache file.
- If the metadata server returns a 404 error, this means that OS Login
is not enabled. Create a special error code for this and do not log an
error if we see this code.
- If the metadata server returns an error, don't update the cache file
and log and error. If no cache file exists, add an empty one.
=> Update logic in the cache_refresh binary

src/cache_refresh/cache_refresh.cc
fixes a bug where users vector grows continuously, producing incorrect group memberships
=> clear users vector

src/cache_refresh/cache_refresh.cc, src/nss/nss_oslogin.cc, src/oslogin_utils.cc, test/oslogin_utils_test.cc
* modify `ParseJsonToUsers` to not return error if the 'usernames' attribute is missing, as this is the normal behavior for an empty group.
* modify callers not to assume users vector has members
=> support empty groups

src/cache_refresh/cache_refresh.cc
add std::unitbuf[1] to cause each write to be immediately flushed. 
[1]: https://en.cppreference.com/w/cpp/io/manip/unitbuf
=> flush each group member write

src/Makefile, src/authorized_keys/authorized_keys_sk.cc, src/include/oslogin_utils.h, src/oslogin_utils.cc
add a new binary `google_authorized_keys_sk` which acts the same as `google_authorized_keys`, but only for security keys.
=> add authorized_keys_sk

src/authorized_keys/authorized_keys.cc
contains definition for exit()
=> include cstdlib for exit

src/authorized_keys/authorized_keys.cc, src/authorized_keys/authorized_keys_sk.cc
* Add signal handler to google_authorized_keys_sk.
* replace exit(3) with _Exit(2) as it is a signal-handler safe function.
* Replace signal(2) with sigaction(2) for portability and to avoid setting feature test macros, per documentation:
> "The semantics when using **signal**() to establish a signal handler vary across systems (and POSIX.1 explicitly permits this variation); **do not use it for this purpose**."
(emphasis in original)
=> use sigaction for signals

src/include/oslogin_utils.h, src/oslogin_utils.cc
The cache_refresh binary is already written to treat ENOMSG to mean OS Login is functioning but there are no groups in the response, and logs differently in this case. This PR just plumbs errno through to the relevant JSON parsing function so we can disambiguate between no groups in response and invalid response/failure to parse response.
=> don't log error when no groups exist

Makefile, src/Makefile, test/Makefile
- consistent formating across all files (space between a target and a semicolon)
- add targets for installing build dependencies on RHEL-like systems (this is useful for quick creation of a build/dev environment)
- the clean target now cleans a bit better
- installation of man-pages doesn't ask for confirmations on overrides
- clearly defined a default target
=> Cleanup Makefiles

src/include/oslogin_utils.h, src/oslogin_utils.cc
Remove duplicates in a header include and a function declaration.
=> PAM cleanup: remove duplicates

src/pam/pam_oslogin_admin.cc, src/pam/pam_oslogin_login.cc
Test if files were opened for writing successfully.
This is important because directories are created by `guest-agent` which is a separate software product.
=> Check open files

src/pam/pam_oslogin_login.cc
Customer's request (b/278036791):
Current OS login SSH flow displays to a user the following prompt to provide the OTP:
`Enter your security code by visiting g.co/sc:`
This is cumbersome as one can't access the service directly from the terminal by eg. cmd+double-click on MacOS.
If the user were provided the full URL like shown below it would make the job easier:
`Enter your security code by visiting https://g.co/sc:`
=> Improve the URL in 2fa prompt

.gitignore, src/Makefile, src/include/oslogin_sshca.h, src/pam/oslogin_sshca.cc, src/pam/pam_oslogin_admin.cc, src/pam/pam_oslogin_login.cc, test/Makefile, test/oslogin_sshca_test.cc, third_party/include/openbsd.h
Introduce required code to extract the fingerprint content from openssh cert format. The format documentation can be found here:
https://cvsweb.openbsd.org/src/usr.bin/ssh/PROTOCOL.certkeys?annotate=HEAD
=> byoid: extract and apply the ca fingerprint to policy call

src/pam/oslogin_sshca.cc, test/Makefile, test/oslogin_sshca_test.cc
We didn't account that the SSH_AUTH_INFO_0 variable format has a method
token and that it can have multiple lines - even that it's unlikely
to happen with oslogin use cases it's healthier to account for that.
The tests were changed to reflect the actual implementation change.
Additionally this patch also changes the internal function's signature
to be prefixed with _.
=> sshca: support method token and handle multi line

test/oslogin_sshca_test.cc
Test fingerprint parsing with certs containing all default ssh-keygen extensions + the byoid fingerprint.
=> sshca: add tests with fingerprint and multiple extensions

src/oslogin_utils.cc
We observed an inconsistency of behavior of access() across linux systems, to work that around we are changing it to use stat() instead.
=> utils: change FileExists() to use stat() instead of access()

src/include/oslogin_utils.h
Given the current headers included and suse 12's headers current state we'll end up not having stdio.h and stdlib.h in cases we expect them to be available so we need to explicitly include them.
=> build: fix suse build

packaging/debian/control, packaging/google-compute-engine-oslogin.spec
Force guest-agent to be present in at least a given version.
=> packaging: make the dependency explicit

src/Makefile
Remove include/oslogin_sshca.h from the list of dependecies. It is passed to the linker command as a part of $^ variable and causes clang build error:
clang: error: clang: cannot specify -o when generating multiple output fileserror:
cannot specify -o when generating multiple output files
=> build: fix clang build

src/Makefile
When updating the COS build we found out that the build system wasn't properly concatenating DESTDIR and the target dirs if DESTDIR didn't end with a slash. The following make call would produce an invalid result:
make DESTDIR=/path/to/target LIBDIR=lib64
One would expect to have lib artifacts installed to /path/to/target/lib64 instead we were installing artifacts to /path/to/targetlib64.
=> build: fix DESTDIR concatenation

src/oslogin_utils.cc
Since these error messages appear in `/var/log/messages`, and do not come with sufficient context identifying them as being uniquely about **OS Login** users, this change adjusts the messages to be clearer and more explicit.
=> Change error messages when checking login policy.

packaging/google-compute-engine-oslogin.spec, src/Makefile, src/include/oslogin_utils.h, src/oslogin_utils.cc, src/pam/pam_oslogin_admin.cc, src/pam/pam_oslogin_login.cc
With this change users can get back to using these pam modules for their own custom pam configurations in a way to differentiate oslogin users (i.e. reported issue #123).
PS: These modules will not be automatically added to google's managed pam configurations by guest-agent.
=> pam: bring back pam's account management implementation

src/oslogin_utils.cc
This change splits out parsing of the "root" element from all the JSON-parsing functions into one shared function, with a bunch of extra logging.
Error handling and logging follows the sample code provided by the json-c library: https://json-c.github.io/json-c/json-c-0.10/doc/html/json__tokener_8h.html#a0d9a666c21879647e8831f9cfa691673
=> Log clearly when the initial parsing of a JSON object fails

src/oslogin_utils.cc, test/oslogin_utils_test.cc
These are returned for incorrect request paramaters (non-utf8, characters not allowed in usernames, etc.) and repeating the request without changing the parameters is pointless. I looked through other return codes from the MDS and no other obviously non-retryable ones jumped out at me other than 405, but 405 would mean there is a logic problem rather than an input problem so we may not want to paper over that one.
Fixes #136
/cc @ericdand @ChaitanyaKulkarni28
=> Don't retry bad request responses

src/Makefile
This MR addresses https://github.com/GoogleCloudPlatform/guest-oslogin/issues/139 by appending flags in the Makefile  instead of assigning.
=> Inherit environment build flags.

src/pam/pam_oslogin_login.cc
Improves logging when a user doesn't have any 2FA methods configured for their Google account.
Fixes #134
=> Log an error when user has no challenges configured

src/Makefile, src/authorized_keys/authorized_keys.cc, src/authorized_keys/authorized_keys_sk.cc, src/authorized_principals/authorized_principals.cc, src/cache_refresh/cache_refresh.cc, src/include/oslogin_sshca.h, src/nss/nss_cache_oslogin.c, src/nss/nss_oslogin.cc, src/oslogin_sshca.cc, src/oslogin_utils.cc, src/pam/pam_oslogin_admin.cc, src/pam/pam_oslogin_login.cc
This change applies the rule in https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes which states that angle brackets should only be used where necessary (i.e. for system libs), and quotes should be heavily preferred. Furthermore, all include paths should be relative to the "source root," in this case `/src/`.
=> Follow the Google style guide by using the "local include style" to include files from this project.

src/Makefile, src/include/oslogin_utils.h, src/oslogin_utils.cc, test/Makefile, test/oslogin_sshca_test.cc, test/oslogin_test.cc, test/oslogin_utils_test.cc
This PR fixes a typing bug where GIDs were being handled as signed 32-bit integers, which would make GIDs exceeding 2^31 incorrectly be printed as negative numbers. It includes a comment explaining why we parse integers as 64-bit (signed) ints using the JSON library, too (spoiler: because the JSON library has no unsigned versions of its functions).
This PR also includes a small improvement to the Makefile, since I noticed that `make clean` was skipping a binary file.
=> Fix a bug where very large GIDs would cause integer overflow errors

src/openbsd-compat/base64.h
`base64.h` had a whole bunch of missing symbols if you tried to build it on its own: no includes, just vibes. 🦄
Since it was borrowed from BSD originally, it also had a few BSD-specific type aliases (e.g. `u_char`) that I'm frankly amazed `g++` didn't complain about. I've replaced these with standard type names or aliases, and added the libraries that contain the functions used here, like `string.h`'s `isspace(char*)` utility.
Finally, this CL also adds the style of fallthrough annotation statement that `clang` expects, with the `[[double braces]]`.
=> Fix base64.h's missing includes and BSD types

src/authorized_keys/authorized_keys.cc, src/authorized_keys/authorized_keys_sk.cc, src/authorized_principals/authorized_principals.cc, src/cache_refresh/cache_refresh.cc, src/include/compat.h, src/include/nss_cache_oslogin.h, src/nss/nss_cache_oslogin.c, src/nss/nss_oslogin.cc, src/oslogin_sshca.cc, src/oslogin_utils.cc, src/pam/pam_oslogin_admin.cc, src/pam/pam_oslogin_login.cc
Proper discipline with `#include` statements makes refactoring much easier in the future, and makes code-tracing much easier.
=> Apply "include what you use," fixing missing include statements broadly.

src/authorized_keys/authorized_keys.cc, src/authorized_keys/authorized_keys_sk.cc, src/authorized_principals/authorized_principals.cc, src/pam/pam_oslogin_admin.cc, src/pam/pam_oslogin_login.cc
This initialization style, borrowed from C99, only performs as expected for *arrays*. For structs, it only initializes the struct's first member to zero, and it leaves the rest alone (unexpectedly!).
Personally, I prefer code to be written in such a way that empty initialization is never necessary (I disagree with the practice of always zero-initializing "just in case" -- you should always _know_ whether you're accessing a variable before it was initialized), but I digress... this incremental improvement will at least fix one more clang error while leaving the code largely as-is.
=> Fix bad struct initialization pattern `= { 0 }`

src/Makefile, src/oslogin_utils.cc
We want to have the opaque include in the case of json lib headers,
we've seen a shift of these header over the years by hiding them
behind json.h allows us to not have to handle backward compatibility
include strategies - being able to build for older systems such as
el8.
=> Fix json include

src/oslogin_utils.cc
This type mismatch led to the weirdest, most opaque trap errors from the clang sanitizer. I actually wasn't able to even get clang to point this problem out to me directly, but thanks to a disassembler and some help from another expert, I was able to fix the issue.
=> Send the correct type to SysLogErr to make the clang sanitizer happy.

src/oslogin_utils.cc
Hey folks, we're working on updating COS to use the newest version of guest-oslogin and we ran into a compilation issue with strings being passed to the logging functions in src/oslogin_utils.cc since our build pipeline uses clang++.
Specifically, passing a string to a variadic function can fail at runtime, and results in the following error when compiling with clang++: `error: cannot pass object of non-trivial type 'string' (aka 'basic_string<char>') through variadic function; call will abort at runtime`
This fixes the issue by passing c-strings to the relevant functions instead of string.
=> Pass c-strings to logging functions
